config/routes.rb
Comics::Application.routes.draw do
  root "books#index"
  resources :books do
    resources :issues
  end

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :issues

  default_scope { order(:name) }

  def issue_count
    issues.count
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :book

  default_scope { order(:number) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    respond_to do |format|
      format.json{ render json: @books.to_json(methods: [:issue_count]) }
      format.html
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    respond_to do |format|
      format.json { render json: @book.to_json(methods: [:issue_count]) }
      format.html
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :cover_image_url)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_book
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /books/123/issues
  # GET /books/123/issues.json
  def index
    @issues = @book.issues
  end

  # GET /books/123/issues/1
  # GET /books/123/issues/1.json
  def show
  end

  # GET /books/123/issues/new
  def new
    @issue = @book.issues.new
  end

  # GET /books/123/issues/1/edit
  def edit
  end

  # POST /books/123/issues
  # POST /books/123/issues.json
  def create
    @issue = @book.issues.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to [@book], notice: 'Issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/123/issues/1
  # PATCH/PUT /books/123/issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to [@book, @issue], notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/123/issues/1
  # DELETE /books/123/issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to book_url(@book) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:book_id])
    end

    def set_issue
      @issue = @book.issues.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:book_id, :number, :title, :cover_image_url, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = :success if type == :notice
      type = :error if type == :alert
      type = :info if type == :info
      type = :block if type == :block
      text = content_tag(:div, link_to("x", "#", :class => "close", "data-dismiss" => "alert") + message, :class => "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Product</legend>

    <%= f.input :name %>
    <%= f.input :cover_image_url %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', books_path(@book), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/books/edit.html.erb
<h1>Editing <%= @book.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% @books.in_groups_of(3, false) do |books| %>
  <div class="row">
    <% books.each do |book| %>
      <div class="span3">
        <h4><%= book.name %> - <%= pluralize(book.issues.count, 'Issue') %></h4>
        <%= link_to book_path(book) do %>
          <%= image_tag book.cover_image_url %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @book.name %>
  <div class="btn-group pull-right">
    <%= link_to 'Edit', edit_book_path(@book), class: "btn" %>
    <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
  </div>
</h1>

<p><%= pluralize(@book.issues.count, 'Issue') %></p>

<p><%= number_to_currency(@book.issues.sum(:price)) %> Total</p>

<div id="book_<%= @book.id %>_issues">
  <% @book.issues.in_groups_of(4, false) do |row_issues| %>
    <div class="row-fluid">
      <% row_issues.each do |issue| %>
        <div class="span3">
          <%= div_for issue do %>
            <h4><%= issue.title %></h4>
            <%= link_to book_issue_path(issue.book, issue) do %>
              <%= image_tag issue.cover_image_url %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<hr>

<%= simple_form_for([@book, @book.issues.new]) do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Product</legend>

    <%= f.input :number %>
    <%= f.input :title %>
    <%= f.input :cover_image_url %>
    <%= f.input :price %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', books_path(@book), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/issues/_form.html.erb
<%= simple_form_for([@book, @issue]) do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Product</legend>

    <%= f.input :number %>
    <%= f.input :title %>
    <%= f.input :cover_image_url %>
    <%= f.input :price %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', books_path(@book), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing <%= @issue.title %></h1>

<%= render 'form' %>

<%= link_to 'Show', book_issue_path(@book, @issue) %> |
<%= link_to 'Back', book_issues_path(@book) %>

app/views/issues/index.html.erb
<h1><%= @book.name %> Issues</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Cover image url</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.number %></td>
        <td><%= issue.title %></td>
        <td><%= issue.cover_image_url %></td>
        <td><%= issue.price %></td>
        <td><%= link_to 'Show', book_issue_path(@book, issue) %></td>
        <td><%= link_to 'Edit', edit_book_issue_path(@book, issue) %></td>
        <td><%= link_to 'Destroy', book_issue_path(@book, issue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_book_issue_path(@book) %>

app/views/issues/new.html.erb
<h1>New <%= @book.name %> Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', book_issues_path(@book) %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @book.name %>
  <div class="btn-group pull-right">
    <%= link_to 'Edit', edit_book_issue_path(@book, @issue), class: "btn" %>
    <%= link_to 'Destroy', book_issue_path(@book, @issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
  </div>
</h1>

<%= image_tag @issue.cover_image_url, class: "pull-right" %>

<p>
  <strong>Book:</strong>
  <%= link_to @book.name, book_path(@book) %>
</p>

<p>
  <strong>Number:</strong>
  <%= @issue.number %>
</p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @issue.price %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Comics" %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="/polymer/polymer.min.js"></script>
    <link rel="import" href="/components/comics-sidebar.html" />
  </head>

  <body>

    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Comics</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "All Books", books_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <comics-sidebar></comics-sidebar>
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&#9763; Utah Ruby User Group, 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>